name: CI/CD Deployment Pipeline

on:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npx prisma generate
      - run: npm run build
      - run: npm run lint
      - run: npx jest --passWithNoTests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Execute Remote SSH Deployment Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/kaban-api

            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            docker-compose -f docker-compose.prod.yml up -d --build

            sleep 5
            docker-compose -f docker-compose.prod.yml exec -T nestjs-app npx prisma migrate deploy
